logs:
  dev:
    base_path: "abfss://medallion@adlsunikarrgodev.dfs.core.windows.net/logs" #root folder for logs in ADLS.
    task_table: "dev_task_logs" # subfolder for each log type.
    pipeline_table: "pipeline_logs" # subfolder for each log type.
  staging:
    base_path: "abfss://medallion@adlsunikargostg.dfs.core.windows.net/logs"
    task_table: "staging_task_logs"
    pipeline_table: "pipeline_logs"
  prod:
    base_path: "abfss://medallion@adlsunikargoprd.dfs.core.windows.net/logs"
    task_table: "prod_task_logs"
    pipeline_table: "pipeline_logs"

